### ISSUE TITLE
Lealone-Bench工具使用问题

### ISSUE THREAD

**Issue by lalalalalaqaq** [codefollower/Lealone-Bench#1]
Lealone-Bench是版本不对么？
多处代码需要
import org.lealone.db.DataBufferFactory
但DataBufferFactory在整个lealone库都没找到

**Comment by codefollower** [comment]
我直接测 lealone 6.0 了，如果测5.0，语言换一个 tag 版本。

**Comment by lalalalalaqaq** [comment]
已解决，感谢，期待大佬lealone 6.0 横空出世
